### ISSUE TITLE
Blank screen when trying to access the dashboard

### ISSUE THREAD

**Issue by tk-nguyen** [wso2/analytics-apim#1114]
**Description:**

Hello, I ran into a problem when I deployed WSO2 Analytics with WSO2 APIM. The Publisher and Dev Portal were running just fine, and APIM was connected to the worker. But when I tried to access the dashboard, it just showed a blank screen and dashboard showed the following error in the console: 
![image](https://user-images.githubusercontent.com/39090621/80206858-5126de80-8657-11ea-8ea7-02cee3bc22bb.png)
I also attached the auth.configs segment in the dashboard `deployment.yaml`
```
auth.configs:
  type: apim
  ssoEnabled: true
  properties:
    adminScope: apim_analytics:admin_carbon.super
    allScopes: apim_analytics:admin apim_analytics:product_manager apim_analytics:api_developer apim
_analytics:app_developer apim_analytics:devops_engineer apim_analytics:analytics_viewer apim_analyti
cs:everyone openid apim:api_view apim:subscribe
    adminServiceBaseUrl: https://<apim hostname>:9443
    adminUsername: admin
    adminPassword: admin
    kmDcrUrl: https://<apim hostname>:9443/client-registration/v0.16/register
    kmTokenUrlForRedirection: https://<apim hostname>:9443/oauth2
    kmTokenUrl: https://<apim hostname>:9443/oauth2
    kmUsername: admin
    kmPassword: admin
    portalAppContext: analytics-dashboard
    businessRulesAppContext : business-rules
    cacheTimeout: 30
    baseUrl: https://<apim hostname>:9643
    grantType: authorization_code
    publisherUrl: https://<apim hostname>:9443
    devPortalUrl: https://<apim hostname>:9443
    externalLogoutUrl: https://<apim hostname>:9443/oidc/logout
```
Everything is running on a same VM on the cloud. Any help will be appreciated!

**Affected Product Version:**
wso2-analytics-3.1.0

**OS, DB, other environment details and versions:**    
Ubuntu 18.04 LTS
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

**Steps to reproduce:**
Just try to access the dashboard after running WSO2 APIM and Analytics

**Related Issues:**

There's #906 but there is no followup on the poster
