### ISSUE TITLE
Starting dashboard profile to access business rules throws a start up error

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#778]
**Description:**
Starting the dashboard profile after commenting the auth configs from deployment.yaml throws the below error at the start up.

`
[2019-11-05 14:16:12,103] ERROR {org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager} - Runtime Exception occurred while calling onAllRequiredCapabilitiesAvailable of component carbon-deployment-service java.lang.NullPointerException
	at org.wso2.carbon.analytics.permissions.internal.dao.PermissionsDAO.hasPermission(PermissionsDAO.java:466)
	at org.wso2.carbon.analytics.permissions.internal.dao.PermissionsDAO.grantPermission(PermissionsDAO.java:305)
	at org.wso2.carbon.analytics.permissions.internal.impl.DefaultPermissionProvider.grantPermission(DefaultPermissionProvider.java:148)
	at org.wso2.carbon.dashboards.core.internal.DashboardMetadataProviderImpl.updateDashboardRoles(DashboardMetadataProviderImpl.java:306)
	at org.wso2.carbon.dashboards.core.internal.DashboardImporter.importDashboards(DashboardImporter.java:99)
	at org.wso2.carbon.dashboards.core.internal.DashboardMetadataProviderImpl.init(DashboardMetadataProviderImpl.java:106)
	at org.wso2.carbon.dashboards.api.internal.DashboardRestApiProvider.getMicroservices(DashboardRestApiProvider.java:102)
	at org.wso2.carbon.uiserver.internal.deployment.listener.RestApiDeployer.collectMicroservices(RestApiDeployer.java:127)
	at org.wso2.carbon.uiserver.internal.deployment.listener.RestApiDeployer.appDeploymentEvent(RestApiDeployer.java:86)
	at org.wso2.carbon.uiserver.internal.io.deployment.ArtifactAppDeployer.publishAppDeploymentEvent(ArtifactAppDeployer.java:154)
	at org.wso2.carbon.uiserver.internal.io.deployment.ArtifactAppDeployer.deploy(ArtifactAppDeployer.java:103)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)`

**Affected Product Version:**
analytics-3.0.0-RC3

**Steps to reproduce:**
1. Take a fresh APIM-Analytics-3.0.0 zip and unzip it.
2.  Go to deployment.yaml and comment the below section.
```
# Authentication configuration
auth.configs:
  type: apim
  ssoEnabled: true
  properties:
    adminScope: apim_analytics:admin_carbon.super
    allScopes: apim_analytics:admin apim_analytics:product_manager apim_analytics:api_developer apim_analytics:app_developer apim_analytics:devops_engineer apim_analytics:analytics_viewer apim_analytics:everyone openid apim:api_view apim:subscribe
    adminServiceBaseUrl: https://localhost:9443
    adminUsername: admin
    adminPassword: admin
    kmDcrUrl: https://localhost:9443/client-registration/v0.15/register
    kmTokenUrlForRedirection: https://localhost:9443/oauth2
    kmTokenUrl: https://localhost:9443/oauth2
    kmUsername: admin
    kmPassword: admin
    portalAppContext: analytics-dashboard
    businessRulesAppContext : business-rules
    cacheTimeout: 900
    baseUrl: https://localhost:9643
    grantType: authorization_code
    publisherUrl: https://localhost:9443
    #storeUrl: https://localhost:9443
```
3. Start the dashboard profile.
4. Above error will be thrown at the start up.

Issue occurs when we try to deploy the two dashboards which are inside the /wso2am-analytics-3.0.0/wso2/dashboard/resources/dashboards folder. To get rid of this error we need to remove these two dashboards before starting the pack.
But we need a proper fix for this issue.
