### ISSUE TITLE
SSO support for Business Rules component

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#836]
**Description:**
Even though we have added the following config by default in the deployment.yaml file of the dashboard profile, SSO support is not there for business rules. Therefore we cannot log into BR with the default configuration that we ship.

```yaml
auth.configs:
  type: apim
  ssoEnabled: true
  properties:
    adminScope: apim_analytics:admin_carbon.super
    allScopes: apim_analytics:admin apim_analytics:product_manager apim_analytics:api_developer apim_analytics:app_developer apim_analytics:devops_engineer apim_analytics:analytics_viewer apim_analytics:everyone openid apim:api_view apim:subscribe
    adminServiceBaseUrl: https://localhost:9443
    adminUsername: admin
    adminPassword: admin
    kmDcrUrl: https://localhost:9443/client-registration/v0.15/register
    kmTokenUrlForRedirection: https://localhost:9443/oauth2
    kmTokenUrl: https://localhost:9443/oauth2
    kmUsername: admin
    kmPassword: admin
    portalAppContext: analytics-dashboard
    businessRulesAppContext : business-rules
    cacheTimeout: 900
    baseUrl: https://localhost:9643
    grantType: authorization_code
    publisherUrl: https://localhost:9443
    #storeUrl: https://localhost:9443
```

**Affected Product Version:**
Analytics 3.0.0

**Steps to reproduce:**
1. Start AM pack and then start the AM-analytics pack with dashboard profile
2. Try to login to BR
